[platformio]
src_dir = .
include_dir = Core/Inc

[env:nucleo_h753zi]
platform = ststm32
board = nucleo_h753zi
framework = stm32cube
upload_protocol = stlink

build_flags =
    -ICore/Inc
    -IDrivers/BSP/STM32H7xx_Nucleo
    -DSTM32H753xx

build_src_filter =
    +<Core/Src/>
    +<Drivers/BSP/STM32H7xx_Nucleo/stm32h7xx_nucleo.c>
    -<Core/Src/sysmem.c>
    -<Core/Src/syscalls.c>